# **PART I**

***TASK 1***

Theo Symonds. Lab 2

***TASK 2***

In [ ]:
print("hello world")
3 + 3

hello world

6

***TASK 3***

In [ ]:
13 + 6

19

In [ ]:
45 + 53

98

***TASK 4***

In [ ]:
"the text inside of the quotation marks is a string"

'the text inside of the quotation marks is a string'

In [ ]:
"this is a new string to print"

'this is a new string to print'

***TASK 5***

In [ ]:
# this is a comment
"this is a string below a comment"

'this is a string below a comment'

In [ ]:
"this is a string with a comment to the side" # this is another comment

'this is a string with a comment to the side'

***TASK 6***

In [ ]:
# this is how the number 90 is spoken in French (quatre-vingt dix = four twenties and ten)
(4 * 20) + 10

90

***TASK 7***

In [ ]:
# Assign an integer value representing age
my_age = 27

# Assign a string value representing first name
first_name = "Theo"

# Assign a string value representing last name
last_name = "Symonds"

# Calculate age in five years using a math operator
my_age_in_five_years = my_age + 5

# print my age in five years
print(my_age_in_five_years)

32

***TASK 8***

In [ ]:
montana_cites = ["Missoula", "Helena", "Bozeman", "Kalispell","Billings", "Whitefish", "St. Regis", "Columbia Falls"]

# the sixth city
MTcity_6 = montana_cites[5]
print(MTcity_6)

# the first two cities
MTcity_FirstTwo = montana_cites[0:2]
print(MTcity_FirstTwo)

Whitefish
['Missoula', 'Helena']

***TASK 9***

In [ ]:
import numpy as np

my_matrix = np.arange(1, 10).reshape(3, 3)
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
my_matrix[0, 2] #print the value on row 1 (0 in Python) and column 3 (2 in python)

np.int64(3)

In [ ]:
print(my_matrix[2, 0]) #print the value on row 3 (2 in Python) and column 1 (0 in python)

7

***TASK 10***

In [ ]:
import pandas as pd

name = ["Vanessa", "Andrew", "Claire", "Selina"]
age = [29, 28, 22, 25]

my_data_frame = pd.DataFrame({"name": name,"age": age})
my_data_frame

      name  age
0  Vanessa   29
1   Andrew   28
2   Claire   22
3   Selina   25

In [ ]:
# show all four ages
ages = my_data_frame["age"]
ages

0    29
1    28
2    22
3    25
Name: age, dtype: int64

In [ ]:
# show names associated with ages
my_data_frame

      name  age
0  Vanessa   29
1   Andrew   28
2   Claire   22
3   Selina   25



---

# **PART II**

In [ ]:
import ee

In [ ]:
import ee

ee.Authenticate(force=True)
ee.Initialize(project='fors351labs-489406')

In [ ]:
# Trigger the authentication flow.
ee.Authenticate()

# Typically the project ID is the same name but all lowercase.
# Note you project will have a unique name! Not the one I use below
# Go to https://code.earthengine.google.com/ to see your exact project name
ee.Initialize(project='fors351labs-489406')

In [ ]:
# Print the elevation of Mount Everest.
dem = ee.Image('USGS/SRTMGL1_003')
xy = ee.Geometry.Point([86.9250, 27.9881])
elev = dem.sample(xy, 30).first().get('elevation').getInfo()
print('Mount Everest elevation (m):', elev)

Mount Everest elevation (m): 8729

***TASK 11***

In [ ]:
# Print the elevation of other location.
dem = ee.Image('USGS/SRTMGL1_003')
xy = ee.Geometry.Point([47.3213, 28.9881])
elev = dem.sample(xy, 30).first().get('elevation').getInfo()
print('Other elevation (m):', elev)

Other elevation (m): 233

***TASK 12***

In [ ]:
# Import the Image function from the IPython.display module.
from IPython.display import Image

# Display a thumbnail of global elevation.
Image(url = dem.updateMask(dem.gt(0))
  .getThumbURL({'min': 0, 'max': 4000, 'dimensions': 512,
                'palette': ['006633', 'E5FFCC', '662A00', 'D8D8D8', 'F5F5F5']}))

***TASK 13***

In [ ]:
# Import the geemap library.
import geemap

# Set visualization parameters.
vis_params = {
  'min': 0,
  'max': 4000,
  'palette': ['006633', 'E5FFCC', '662A00', 'D8D8D8', 'F5F5F5']}

# Create a map object.
m = geemap.Map(center=[20, 0], zoom=3)

# Add the elevation model to the map object.
m.add_ee_layer(dem.updateMask(dem.gt(0)), vis_params, 'DEM')

# Display the map.
display(m)

Map(center=[20, 0], controls=(WidgetControl(options=['position', 'transparent_bg'], widget=SearchDataGUI(child…



---

# **PART III**

***TASK 14***

In [ ]:
dataset = ee.ImageCollection('LANDSAT/LC08/C02/T1_L2').filterDate(
    '2021-07-01', '2021-08-01'
) #this code chooses our image and the date range

# Applies scaling factors.
def apply_scale_factors(image):
  optical_bands = image.select('SR_B.').multiply(0.0000275).add(-0.2)
  thermal_bands = image.select('ST_B.*').multiply(0.00341802).add(149.0)
  return image.addBands(optical_bands, None, True).addBands(
      thermal_bands, None, True
  )

#  Satellite data is stored as scaled integers, not real physical values.
#     Without this step, pixel values would not be physically meaningful.
# Optical bands (SR_B*) are converted to unitless surface reflectance
#     Thermal bands (ST_B*) are converted to temperature in Kelvin
# We used a function because the dataset contains many images. If we applied
#     this to every image the code would get very redundant.

dataset_scaled = dataset.map(apply_scale_factors)

#you will now visualize the data in RGB
visualization = {
    'bands': ['SR_B4', 'SR_B3', 'SR_B2'],
    'min': 0.0,
    'max': 0.3,
}

m = geemap.Map()
m.set_center(-113.9940, 46.8721, 8)
m.add_layer(dataset_scaled, visualization, 'True Color (432)')
m

Map(center=[46.8721, -113.994], controls=(WidgetControl(options=['position', 'transparent_bg'], widget=SearchD…

***TASK 15***

In [ ]:
# Preprocessing function
def preprocess_landsat8(image):
    # QA masks
    qa_mask = image.select('QA_PIXEL').bitwiseAnd(int('11111', 2)).eq(0)
    # Each 1 in the above line corresponds to each bitmask value (i.e., Fill,
    # Dilated Cloud, Cirrius (high confidence), Cloud, and Cloud Shadow). The 2
    # tells us to interpret this as a base-2 (binary) number. The eq(0) indicates
    # we only want to include the highest value data.
    saturation_mask = image.select('QA_RADSAT').eq(0)

    # Apply scaling factors
    optical = image.select('SR_B.*').multiply(0.0000275).add(-0.2)
    thermal = image.select('ST_B.*').multiply(0.00341802).add(149.0)

    return (
        image
        .addBands(optical, None, True)
        .addBands(thermal, None, True)
        .updateMask(qa_mask)
        .updateMask(saturation_mask)
    )

dataset_filtered = dataset.map(preprocess_landsat8)

m = geemap.Map()
m.set_center(-113.9940, 46.8721, 8)
m.add_layer(dataset_filtered, visualization, 'True Color (432)')
m

Map(center=[46.8721, -113.994], controls=(WidgetControl(options=['position', 'transparent_bg'], widget=SearchD…

***TASK 16***

In [ ]:
# Define the region of interest
# Example: Missoula Region
region = ee.Geometry.Rectangle([
    -114.35,  # West
    46.70,    # South
    -113.75,  # East
    47.05     # North
])

mso = dataset_filtered.mean().clip(region)

m = geemap.Map()
m.add_layer(mso, visualization, 'True Color (432)')
m

Map(center=[0, 0], controls=(WidgetControl(options=['position', 'transparent_bg'], widget=SearchDataGUI(childr…

In [ ]:
# Define the region of interest
region = ee.Geometry.Rectangle([
    -114.35,  # West
    46.70,    # South
    -113.75,  # East
    47.05     # North
])

mso = dataset_filtered.mean().clip(region)

m = geemap.Map()
m.add_layer(mso, visualization, 'True Color (432)')
m.addLayer(region, {}, 'Region')
m.centerObject(region, 10)
m

Map(center=[46.87520162419828, -114.05000000000038], controls=(WidgetControl(options=['position', 'transparent…

***TASK 17***

In [ ]:
ndvi_expression = "(NIR - Red) / (NIR + Red)"

#mso is the name of your map you created from the ROI above!
ndvi = mso.expression(ndvi_expression,{
    'NIR': mso.select('SR_B5'),
    'Red': mso.select('SR_B4')})


# Import the Image function from the IPython.display module.
from IPython.display import Image

#note you can play around with the visualization if you like
ndvi_vis_params = {
    'min': 0,
    'max': 1,
    'dimensions': 1000,
    'region': region,
    'palette': ['A50026', 'D73027', 'F46D43', 'FDAE61', 'FEE08B',
                'FFFFBF','D9EF8B','A6D96A','66BD63','1A9850']
}

# Save as a variable and display the image.
ndvi_url = ndvi.getThumbURL(ndvi_vis_params)

display(Image(url=ndvi_url))

***TASK 18***

1. What do the greens and oranges/reds represent in this image?
> The greens represent areas with higher NDVI values, meaning healthier or denser vegetation. The oranges/reds represent lower NDVI values, meaning little vegetation, sparse vegetation, bare ground, urban surfaces, or possibly water.

2. What features have the most noticable high or low NDVI values?
> Dense, healthy vegetation has the highest NDVI values. Areas with little or no vegetation, such as bare soil, developed land, rock, or water, have the lowest NDVI values.

3. How would you expect this NDVI image to change in the winter?
> In winter, I would expect NDVI values to be lower because there is usually less active vegetation. Deciduous plants lose their leaves, grasses may be dormant, and snow cover can further reduce the appearance of healthy vegetation.

4. How do you find working in GEE/Google Colab?
> I really like working with Google Colab, and I think it has a small advantage over jupyter notebooks in the way it can be shared with the general public.  When using jupyter notebooks in the past, I find that a small pain point with sharing the code with people is that it is sometimes complicated to execute the prerequsite pip installs for the library and packages that are needed. It seems that with Google Colab, the cloud-based system makes it easier to manage dependencies for running scripts.